# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Deploy"

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
    tags:
      - "**"

jobs:
  deploy:
    name: "Deploy"

    runs-on: "ubuntu-latest"

    env:
      DOCKER_IMAGE: "ergebnis/composer-root-version-action"
      DOCKER_USERNAME: "ergebnis"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.2"

      - name: "Build Docker image"
        run: "docker build --tag ${{ env.DOCKER_IMAGE }}:latest ."

      - name: "Docker Login"
        if: "'refs/heads/main' == github.ref || startsWith(github.ref, 'refs/tags/')"
        run: "echo ${{ secrets.DOCKER_PASSWORD }} | $(which docker) login --password-stdin --username ${{ env.DOCKER_USERNAME }}"

      - name: "Push Docker image (latest)"
        if: "'refs/heads/main' == github.ref || startsWith(github.ref, 'refs/tags/')"
        run: "docker push ${{ env.DOCKER_IMAGE }}:latest"

      - name: "Determine tag"
        if: "startsWith(github.ref, 'refs/tags/')"
        id: "determine-tag"
        run: "echo \"::set-output name=tag::${GITHUB_REF#refs/tags/}\""

      - name: "Tag Docker image (versioned)"
        if: "startsWith(github.ref, 'refs/tags/')"
        run: "docker tag ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_IMAGE }}:${{ steps.determine-tag.outputs.tag }}"

      - name: "Push Docker image (versioned)"
        if: "startsWith(github.ref, 'refs/tags/')"
        run: "docker push ${{ env.DOCKER_IMAGE }}:${{ steps.determine-tag.outputs.tag }}"

      - name: "Docker Logout"
        if: "'refs/heads/main' == github.ref || startsWith(github.ref, 'refs/tags/')"
        run: "docker logout"

      - name: "Create release"
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "actions/create-release@v1.1.3"
        env:
          GITHUB_TOKEN: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
        with:
          draft: false
          prerelease: false
          release_name: "${{ steps.determine-tag.outputs.tag }}"
          tag_name: "${{ steps.determine-tag.outputs.tag }}"
